<!DOCTYPE html>
<head>
	<meta charset="UTF-8">
	<title><?=$titre;?></title>
	<html lang="en">

	<link rel="stylesheet" type="text/css" href="public/styles/style.css">
	<link rel="stylesheet" type="text/css" href="public/bootstrap/css/bootstrap.min.css">
</head>
<body>
	

		<?php require ("apps/header.php");?>
		<?php require ("apps/menu.php");?>
		<?php require ("apps/content.php");?>
		<?php require ("apps/footer.php");?>
		
	